name: robotics-class
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.6
  - scikit-image=0.17.2
  - scipy=1.5.3
  - tqdm
  - numpy=1.19.5
  - opencv=4.5.1
  - pytorch=1.8.0
  - torchvision=0.9.0
  - pytest=6.2.2
