channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.6.9
  - numba=0.45.1
  - scikit-image=0.15.0
  - scipy=1.3.1
  - tqdm=4.32.1
  - numpy==1.17.2
  - opencv=3.4.2
  - pytorch
  - torchvision
  - pytest